apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  selector:
    matchLabels:
      app: second-app
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
      - name: second-node
        image: ultracloudkris/mynodeapp

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
